### ISSUE TITLE
No RSS feed

### ISSUE THREAD

**Issue by ghost** [pzemtsov/pzemtsov.github.io#1]
I wanted to subscribe to your blog, but I noticed I can't use my RSS reader to follow your page. Can you setup an RSS feed?

**Comment by pzemtsov** [comment]
Thanks for pointing this out. I'll set up RSS as soon as I can

**Comment by ghost** [comment]
I just noticed you updated your site. Feedly read the feed just fine, and I see the RSS Feed link in the footer. Thanks for adding it!
